import Link from "next/link";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header>
          <Link href='/redirect'>리다이렉트</Link>
          <Link href='/basePath'>테스트</Link>
          <Link href='/'>Home</Link>
          <Link href='/env'>env</Link>
          <Link href='/rewrite'>리라이트</Link>
        </header>
        {children}
      </body>
    </html>
  );
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
